version: '3.8'

services: 
	mariadb:
		build: ./requirements/mariadb
	nginx:
		build: ./requirements/nginx
	wordpress:
		build: ./requirements/wordpress

volume:
	mariadb_data:

	wordpress_data:

networks:
	inception_network:

